### ISSUE TITLE
Welcome back !

### ISSUE THREAD

**Issue by wanderrer** [KASH4/qbus#2]
Hey guys, welcome back to the game :) Will you maintain the code for Qb and updated the source to be compatible with OneSync ? Or is this a friendly "here's the source everybody is looking for" ? Heh.. Anyways, whatever you are choosing to do, I have to say that this is one of the best frameworks that I have ever seen !

**Comment by qbcore-framework** [comment]
Depending on how FiveM decides, this repo may be maintained. Otherwise not.

**Comment by wanderrer** [comment]
FiveM ? How are they involved with Qbus ?

**Comment by qbcore-framework** [comment]
Depending on what they decide, we will be going public on their forum

**Comment by KASH4** [comment]
Appearently some people of the FiveM community have been involved with some scandals using our framework, however after some time I decided to release it because its no point for people to buy something which is pretty much available everywhere. I do not condone anyone selling this framework, selling resources for this framework or variations of this framework. I don't want my work to be involved in shitty scandals I or FiveM can get a grip on.
